// 语义标签映射 —— 由像素级扫描（2026-06-10）生成，覆盖 DCSS CC0 FreeArtLib 全部主要子目录。
// 搜索增益：补充名字里读不出的语义（元素、尺寸、威胁、用途），让"fire"/"boss"/"flying"跨分类可检索。
//
// CAT_TAGS:     cat 或 cat/sub 路径 → 该路径下所有资产共享的标签
// SUBJECT_TAGS: subject 主题名 → 该主题特有的语义标签
//
// artlibTokens() 自动合并两者 + 原有路径词段，无需重跑 index.json。

/** 分类级标签：某个 cat 或 cat/sub 下所有资产共享 */
export const CAT_TAGS: Record<string, string[]> = {
  // ── monsters ──────────────────────────────────────────────────────────────
  'monster':                  ['monster', 'enemy', 'hostile'],
  'monster/animals':          ['animal', 'natural', 'biological', 'organic'],
  'monster/undead':           ['undead', 'dark', 'necromancy', 'death', 'cold'],
  'monster/undead/skeletons': ['skeleton', 'undead', 'bone'],
  'monster/undead/zombies':   ['zombie', 'undead', 'rotten'],
  'monster/undead/spectrals': ['spectral', 'ghost', 'intangible', 'undead'],
  'monster/undead/simulacra': ['simulacrum', 'ice', 'cold', 'undead'],
  'monster/demons':           ['demon', 'hell', 'chaotic', 'evil', 'summoned'],
  'monster/draconic':         ['draconic', 'humanoid_dragon', 'scales'],
  'monster/dragons':          ['dragon', 'large', 'breath_weapon', 'flying', 'reptile'],
  'monster/nonliving':        ['nonliving', 'construct', 'no_blood', 'cannot_poison'],
  'monster/holy':             ['holy', 'divine', 'celestial', 'white', 'light', 'gold'],
  'monster/unique':           ['unique', 'named', 'boss', 'special'],
  'monster/panlord':          ['panlord', 'demon', 'boss', 'large', 'unique'],
  'monster/abyss':            ['abyss', 'aberrant', 'chaotic', 'unusual'],
  'monster/amorphous':        ['amorphous', 'blob', 'no_blood', 'unusual'],
  'monster/aquatic':          ['aquatic', 'water', 'fish'],
  'monster/eyes':             ['eye', 'aberrant', 'gaze', 'unusual', 'floating'],
  'monster/fungi_plants':     ['plant', 'fungi', 'organic', 'stationary', 'unusual'],
  'monster/demonspawn':       ['demonspawn', 'humanoid', 'demon_adjacent', 'scales'],
  'monster/spriggan':         ['spriggan', 'small', 'fey', 'fast'],
  'monster/statues':          ['statue', 'nonliving', 'construct', 'stone'],
  'monster/vault':            ['vault', 'guard', 'armored', 'humanoid'],
  'monster/aberration':       ['aberration', 'aberrant', 'unusual', 'chaotic'],
  'monster/tentacles':        ['tentacle', 'aquatic', 'aberrant', 'large', 'no_blood'],

  // ── items ──────────────────────────────────────────────────────────────────
  'item':                     ['item', 'loot', 'equippable'],
  'item/weapon':              ['weapon', 'melee', 'equippable'],
  'item/weapon/artefact':     ['weapon', 'artefact', 'unique', 'enchanted', 'rare'],
  'item/weapon/ranged':       ['weapon', 'ranged', 'projectile'],
  'item/armor':               ['armor', 'defense', 'equippable'],
  'item/armor/artefact':      ['armor', 'artefact', 'unique', 'enchanted', 'rare'],
  'item/armor/torso':         ['armor', 'torso', 'chest'],
  'item/armor/headgear':      ['armor', 'headgear', 'helmet', 'head'],
  'item/armor/hands':         ['armor', 'hands', 'gloves', 'gauntlet'],
  'item/armor/feet':          ['armor', 'feet', 'boots'],
  'item/armor/shields':       ['armor', 'shield', 'defense', 'block'],
  'item/armor/bardings':      ['armor', 'barding', 'mount', 'dragon_adjacent'],
  'item/armor/back':          ['armor', 'back', 'cloak_adjacent'],
  'item/amulet':              ['amulet', 'jewelry', 'neck', 'magic_item'],
  'item/amulet/artefact':     ['amulet', 'artefact', 'unique', 'rare'],
  'item/ring':                ['ring', 'jewelry', 'finger', 'magic_item'],
  'item/ring/artefact':       ['ring', 'artefact', 'unique', 'rare'],
  'item/book':                ['book', 'spellbook', 'magic', 'knowledge'],
  'item/book/artefact':       ['book', 'artefact', 'unique', 'rare'],
  'item/potion':              ['potion', 'consumable', 'bottle', 'flask'],
  'item/food':                ['food', 'consumable', 'hunger'],
  'item/scroll':              ['scroll', 'consumable', 'paper', 'magic_item'],
  'item/wand':                ['wand', 'magic_item', 'ranged', 'charge'],
  'item/rod':                 ['rod', 'magic_item', 'staff_type'],
  'item/staff':               ['staff', 'magic_item', 'melee', 'two_handed'],
  'item/gold':                ['gold', 'currency', 'wealth'],
  'item/misc':                ['misc_item', 'unusual'],
  'item/misc/runes':          ['rune', 'objective', 'endgame', 'valuable'],

  // ── dungeon ────────────────────────────────────────────────────────────────
  'dungeon':                  ['dungeon', 'terrain', 'tile'],
  'dungeon/floor':            ['floor', 'walkable', 'ground'],
  'dungeon/floor/grass':      ['floor', 'grass', 'natural', 'outdoor', 'green'],
  'dungeon/floor/sigils':     ['floor', 'sigil', 'magical', 'rune', 'arcane'],
  'dungeon/wall':             ['wall', 'solid', 'impassable'],
  'dungeon/wall/abyss':       ['wall', 'abyss', 'chaotic', 'aberrant', 'multicolor'],
  'dungeon/altars':           ['altar', 'divine', 'religion', 'interact', 'worship'],
  'dungeon/doors':            ['door', 'passage', 'interactive'],
  'dungeon/gateways':         ['gateway', 'portal', 'special', 'transition'],
  'dungeon/shops':            ['shop', 'interact', 'commerce'],
  'dungeon/statues':          ['statue', 'dungeon_feature', 'stone', 'nonliving'],
  'dungeon/traps':            ['trap', 'hazard', 'interact', 'hidden'],
  'dungeon/trees':            ['tree', 'plant', 'natural', 'outdoor'],
  'dungeon/vaults':           ['vault', 'special_room', 'reward'],
  'dungeon/water':            ['water', 'aquatic', 'terrain', 'liquid'],

  // ── effect ─────────────────────────────────────────────────────────────────
  'effect':                   ['effect', 'vfx', 'animation', 'particle'],

  // ── gui ────────────────────────────────────────────────────────────────────
  'gui':                      ['gui', 'ui', 'interface'],
  'gui/spells':               ['spell_icon', 'magic', 'ability', 'gui'],
  'gui/spells/fire':          ['spell_icon', 'fire', 'flame', 'heat'],
  'gui/spells/ice':           ['spell_icon', 'ice', 'cold', 'frost'],
  'gui/spells/earth':         ['spell_icon', 'earth', 'stone', 'rock'],
  'gui/spells/air':           ['spell_icon', 'air', 'wind', 'lightning', 'electric'],
  'gui/spells/necromancy':    ['spell_icon', 'necromancy', 'undead', 'death', 'dark'],
  'gui/spells/summoning':     ['spell_icon', 'summoning', 'summon', 'conjure'],
  'gui/spells/conjuration':   ['spell_icon', 'conjuration', 'force', 'magic_bolt'],
  'gui/spells/enchantment':   ['spell_icon', 'enchantment', 'buff', 'debuff'],
  'gui/spells/translocation': ['spell_icon', 'translocation', 'teleport', 'blink'],
  'gui/spells/transmutation': ['spell_icon', 'transmutation', 'transform', 'polymorph'],
  'gui/spells/poison':        ['spell_icon', 'poison', 'venom'],
  'gui/spells/divination':    ['spell_icon', 'divination', 'reveal', 'sight'],
  'gui/spells/monster':       ['spell_icon', 'monster_spell', 'special'],
  'gui/spells/disciplines':   ['spell_icon', 'discipline', 'combat', 'special'],
  'gui/spells/components':    ['spell_icon', 'component', 'material', 'special'],
  'gui/abilities':            ['ability', 'gui', 'active'],
  'gui/skills':               ['skill', 'gui', 'passive', 'training'],
  'gui/invocations':          ['invocation', 'divine', 'gui'],
  'gui/commands':             ['command', 'action', 'gui'],
  'gui/tabs':                 ['tab', 'navigation', 'gui'],
  'gui/startup':              ['startup', 'menu', 'gui'],

  // ── player paperdoll ───────────────────────────────────────────────────────
  'player':                   ['player', 'paperdoll', 'sprite'],
  'player/base':              ['player', 'body', 'base', 'humanoid'],
  'player/body':              ['player', 'torso', 'armor_visual', 'paperdoll'],
  'player/head':              ['player', 'head', 'helmet_visual', 'paperdoll'],
  'player/hair':              ['player', 'hair', 'cosmetic', 'paperdoll'],
  'player/beard':             ['player', 'beard', 'cosmetic', 'paperdoll'],
  'player/gloves':            ['player', 'gloves', 'hands_visual', 'paperdoll'],
  'player/boots':             ['player', 'boots', 'feet_visual', 'paperdoll'],
  'player/cloak':             ['player', 'cloak', 'back', 'paperdoll'],
  'player/hand_right':        ['player', 'weapon_visual', 'held', 'paperdoll'],
  'player/hand_right/artefact': ['player', 'artefact', 'weapon_visual', 'rare'],
  'player/hand_right/misc':   ['player', 'misc_held', 'paperdoll'],
  'player/hand_left':         ['player', 'offhand', 'shield_visual', 'paperdoll'],
  'player/hand_left/misc':    ['player', 'offhand_misc', 'paperdoll'],
  'player/legs':              ['player', 'legs', 'lower_body', 'paperdoll'],
  'player/barding':           ['player', 'barding', 'mount', 'paperdoll'],
  'player/draconic_head':     ['player', 'draconic', 'head', 'paperdoll'],
  'player/draconic_wing':     ['player', 'draconic', 'wings', 'flying', 'paperdoll'],
  'player/transform':         ['player', 'transform', 'shapeshifter', 'paperdoll'],
  'player/mutations':         ['player', 'mutation', 'aberrant', 'paperdoll'],
  'player/enchantment':       ['player', 'enchantment', 'buff_visual', 'paperdoll'],
  'player/halo':              ['player', 'halo', 'holy', 'divine', 'paperdoll'],
  'player/felids':            ['player', 'felid', 'cat', 'paperdoll'],

  // ── misc (decals) ──────────────────────────────────────────────────────────
  'misc':                     ['decal', 'overlay', 'environmental'],
  'misc/blood':               ['blood', 'gore', 'decal', 'death_marker'],
  'misc/brands':              ['brand', 'overlay', 'enchant_visual'],
  'misc/numbers':             ['number', 'digit', 'hud', 'quantity', 'overlay'],

  // ── emissaries (DCSS 神明 — 分体精灵 top+bottom) ──────────────────────────
  'emissaries':               ['deity', 'god', 'divine', 'npc', 'two_tile', 'large'],

  // ── cardgame ──────────────────────────────────────────────────────────────
  'cardgame':                 ['card', 'balatro', 'joker', '小丑牌'],
  'cardgame/card':            ['card', 'balatro', 'joker', 'artwork', '小丑牌'],
};

/** 主题级标签：特定 subject 名称的语义标签（跨分类生效） */
export const SUBJECT_TAGS: Record<string, string[]> = {
  // ── animal monsters ────────────────────────────────────────────────────────
  adder:              ['snake', 'reptile', 'small', 'poison'],
  alligator:          ['reptile', 'large', 'aquatic', 'melee'],
  anaconda:           ['snake', 'reptile', 'large', 'constrict'],
  ball_python:        ['snake', 'reptile', 'small'],
  basilisk:           ['reptile', 'petrify', 'gaze', 'medium'],
  bat:                ['flying', 'small', 'mammal'],
  bear:               ['mammal', 'large', 'melee'],
  big_fish:           ['aquatic', 'fish', 'medium'],
  blink_frog:         ['amphibian', 'teleport', 'blink'],
  boring_beetle:      ['insect', 'small', 'tunneling', 'earth'],
  boulder_beetle:     ['insect', 'large', 'armored', 'melee'],
  brain_worm:         ['worm', 'small', 'psychic'],
  bumblebee:          ['insect', 'flying', 'small', 'swarm'],
  butterfly:          ['insect', 'flying', 'small', 'passive', 'harmless'],
  catoblepas:         ['beast', 'large', 'petrify', 'gaze', 'dark', 'purple', 'demon'],
  caustic_shrike:     ['bird', 'flying', 'acid', 'ranged'],
  crocodile:          ['reptile', 'large', 'aquatic', 'melee'],
  death_yak:          ['mammal', 'large', 'undead_adjacent', 'cursed'],
  elephant:           ['mammal', 'large', 'charge', 'melee'],
  emperor_scorpion:   ['arthropod', 'large', 'poison', 'melee'],
  fire_bat:           ['flying', 'small', 'fire', 'mammal'],
  fire_crab:          ['arthropod', 'medium', 'fire'],
  ghost_moth:         ['insect', 'flying', 'medium', 'magic_drain', 'purple', 'spectral'],
  giant_ant:          ['insect', 'small', 'swarm'],
  giant_bat:          ['flying', 'medium', 'mammal'],
  giant_beetle:       ['insect', 'medium', 'armored'],
  giant_centipede:    ['arthropod', 'small', 'poison'],
  giant_frog:         ['amphibian', 'medium', 'melee'],
  giant_gecko:        ['reptile', 'small'],
  giant_leech:        ['worm', 'small', 'drain', 'blood'],
  giant_lizard:       ['reptile', 'medium'],
  giant_mosquito:     ['insect', 'flying', 'small', 'drain', 'blood'],
  giant_newt:         ['amphibian', 'tiny'],
  giant_scorpion:     ['arthropod', 'large', 'poison'],
  giant_slug:         ['slug', 'medium', 'acid'],
  giant_snail:        ['gastropod', 'small', 'armored'],
  giant_toad:         ['amphibian', 'large', 'melee'],
  gila_monster:       ['reptile', 'medium', 'poison'],
  grizzly_bear:       ['mammal', 'large', 'melee'],
  hell_hog:           ['mammal', 'medium', 'fire', 'hell', 'demon'],
  hell_hound:         ['mammal', 'medium', 'fire', 'hell', 'canine'],
  hound:              ['mammal', 'small', 'canine', 'melee'],
  ice_beast:          ['elemental', 'ice', 'cold', 'nonliving', 'no_blood'],
  jackal:             ['mammal', 'small', 'canine', 'swarm'],
  // 2026-06-10 拼图复审（Lead 看图）：青色半透明水母，像素无任何电系特征，DCSS 设定亦为毒刺
  // —— 原 electric/lightning 视觉与设定两边都站不住 → 改毒系 + 视觉特征。
  jellyfish:          ['aquatic', 'small', 'translucent', 'poison', 'sting', 'tentacles'],
  jumping_spider:     ['arthropod', 'small', 'leap'],
  killer_bee:         ['insect', 'flying', 'small', 'swarm', 'poison'],
  komodo_dragon:      ['reptile', 'large', 'poison'],
  lava_fish:          ['aquatic', 'fish', 'small', 'fire'],
  lava_worm:          ['worm', 'medium', 'fire'],
  mana_viper:         ['snake', 'reptile', 'medium', 'magic_drain', 'purple'],
  moth_of_wrath:      ['insect', 'flying', 'medium', 'berserk', 'buff'],
  orb_spider:         ['arthropod', 'medium', 'orb', 'dark', 'aberrant'],
  polar_bear:         ['mammal', 'large', 'cold', 'ice'],
  queen_ant:          ['insect', 'medium', 'summoner', 'swarm'],
  queen_bee:          ['insect', 'flying', 'medium', 'summoner', 'swarm'],
  raiju:              ['mammal', 'small', 'lightning', 'electric', 'blue', 'elemental'],
  rat:                ['mammal', 'tiny'],
  red_wasp:           ['insect', 'flying', 'small', 'poison'],
  rock_worm:          ['worm', 'medium', 'earth', 'tunneling'],
  salamander:         ['amphibian', 'medium', 'fire'],
  scorpion:           ['arthropod', 'small', 'poison'],
  shock_serpent:      ['snake', 'reptile', 'medium', 'lightning', 'electric'],
  small_snake:        ['snake', 'reptile', 'tiny'],
  snake:              ['snake', 'reptile', 'small'],
  soldier_ant:        ['insect', 'small', 'swarm'],
  spider:             ['arthropod', 'small', 'web'],
  spiny_frog:         ['amphibian', 'medium', 'poison'],
  tarantella:         ['arthropod', 'medium', 'poison'],
  trapdoor_spider:    ['arthropod', 'small', 'ambush'],
  turtle:             ['reptile', 'small', 'armored'],
  viper:              ['snake', 'reptile', 'small', 'poison'],
  war_dog:            ['mammal', 'medium', 'canine', 'melee'],
  warg:               ['mammal', 'large', 'canine', 'melee'],
  wolf:               ['mammal', 'medium', 'canine', 'pack'],
  worm:               ['worm', 'small'],
  yak:                ['mammal', 'large', 'melee'],

  // ── undead ─────────────────────────────────────────────────────────────────
  ancient_lich:       ['lich', 'boss', 'spellcaster', 'undead_mage', 'glowing', 'large'],
  bone_dragon:        ['dragon', 'undead', 'skeleton', 'large', 'boss'],
  curse_skull:        ['skull', 'flying', 'magic', 'debuff', 'small'],
  eidolon:            ['ghost', 'spectral', 'melee', 'drain'],
  flayed_ghost:       ['ghost', 'humanoid', 'drain', 'necrotic'],
  flying_skull:       ['skull', 'flying', 'small'],
  freezing_wraith:    ['wraith', 'cold', 'ice', 'drain'],
  ghost:              ['ghost', 'spectral', 'humanoid', 'intangible'],
  ghoul:              ['zombie', 'humanoid', 'rotten', 'physical'],
  greater_mummy:      ['mummy', 'boss', 'spellcaster', 'fire'],
  guardian_mummy:     ['mummy', 'large', 'melee'],
  hungry_ghost:       ['ghost', 'drain', 'hunger'],
  jiangshi:           ['undead', 'humanoid', 'drain'],
  lich:               ['lich', 'spellcaster', 'boss', 'undead_mage'],
  mummy:              ['mummy', 'humanoid', 'melee'],
  mummy_priest:       ['mummy', 'spellcaster', 'fire', 'boss'],
  necrophage:         ['zombie', 'humanoid', 'disease', 'infection'],
  phantom:            ['ghost', 'spectral', 'humanoid'],
  phantasmal_warrior: ['ghost', 'spectral', 'melee', 'weapon'],
  profane_servitor:   ['undead', 'spellcaster', 'summoner'],
  revenant:           ['ghost', 'spectral', 'magic', 'fire'],
  rotting_hulk:       ['zombie', 'large', 'disease'],
  shadow:             ['shadow', 'dark', 'intangible'],
  shadow_wraith:      ['wraith', 'shadow', 'dark', 'drain'],
  skeletal_warrior:   ['skeleton', 'humanoid', 'melee', 'weapon'],
  spectral_warrior:   ['ghost', 'spectral', 'melee', 'humanoid'],
  vampire:            ['vampire', 'humanoid', 'drain', 'blood', 'melee'],
  vampire_knight:     ['vampire', 'humanoid', 'melee', 'armored'],
  vampire_mage:       ['vampire', 'humanoid', 'spellcaster'],
  wight:              ['wight', 'humanoid', 'cold'],
  wight_king:         ['wight', 'humanoid', 'boss', 'cold'],
  wraith:             ['wraith', 'spectral', 'drain', 'cold'],
  skeleton_bat:           ['skeleton', 'flying', 'small'],
  skeleton_dragon:        ['skeleton', 'dragon', 'large'],
  skeleton_humanoid_large: ['skeleton', 'humanoid', 'large'],
  skeleton_humanoid_small: ['skeleton', 'humanoid', 'small'],
  skeleton_quadruped_large: ['skeleton', 'quadruped', 'large'],
  skeleton_quadruped_small: ['skeleton', 'quadruped', 'small'],
  zombie_crab:        ['zombie', 'aquatic', 'small'],
  zombie_drake:       ['zombie', 'dragon', 'medium'],
  zombie_hound:       ['zombie', 'canine', 'small'],
  zombie_ogre:        ['zombie', 'humanoid', 'large'],

  // ── demons ─────────────────────────────────────────────────────────────────
  abomination_large:  ['demon', 'large', 'aberrant', 'chaotic', 'amorphous'],
  abomination_small:  ['demon', 'small', 'aberrant', 'chaotic'],
  balrug:             ['demon', 'fire', 'large', 'elite', 'tier1'],
  blue_death:         ['demon', 'large', 'boss', 'electric', 'lightning', 'tier1'],
  blue_devil:         ['demon', 'medium', 'cold', 'ice'],
  cacodemon:          ['demon', 'large', 'elite', 'aberrant', 'boss'],
  chaos_spawn:        ['demon', 'small', 'chaos', 'aberrant', 'multicolor'],
  efreet:             ['demon', 'fire', 'medium', 'elite', 'flame'],
  executioner:        ['demon', 'large', 'elite', 'melee', 'scythe'],
  fiend:              ['demon', 'large', 'boss', 'fire', 'melee', 'tier1'],
  green_death:        ['demon', 'large', 'boss', 'poison', 'tier1'],
  hairy_devil:        ['demon', 'small', 'melee'],
  hell_sentinel:      ['demon', 'large', 'guard', 'melee', 'fire'],
  hellion:            ['demon', 'medium', 'fire', 'melee'],
  hellwing:           ['demon', 'flying', 'medium'],
  ice_devil:          ['demon', 'medium', 'cold', 'ice'],
  ice_fiend:          ['demon', 'large', 'elite', 'cold', 'ice', 'tier1'],
  imp:                ['demon', 'tiny', 'melee', 'summon'],
  iron_devil:         ['demon', 'medium', 'iron', 'metal'],
  iron_imp:           ['demon', 'small', 'iron', 'metal'],
  lemure:             ['demon', 'small', 'weak'],
  lorocyproca:        ['demon', 'medium', 'serpentine', 'constrict'],
  midge:              ['demon', 'tiny', 'flying', 'swarm'],
  neqoxec:            ['demon', 'medium', 'chaos', 'polymorph', 'aberrant'],
  orange_demon:       ['demon', 'medium', 'orange'],
  pit_fiend:          ['demon', 'large', 'elite', 'boss'],
  rakshasa:           ['demon', 'medium', 'illusion', 'humanoid'],
  reaper:             ['demon', 'large', 'elite', 'scythe', 'drain', 'death'],
  red_devil:          ['demon', 'medium', 'fire', 'red'],
  rotting_devil:      ['demon', 'medium', 'disease', 'poison'],
  rust_devil:         ['demon', 'medium', 'rust', 'metal'],
  shadow_demon:       ['demon', 'dark', 'shadow', 'intangible'],
  shadow_fiend:       ['demon', 'large', 'dark', 'shadow', 'elite'],
  shadow_imp:         ['demon', 'small', 'dark', 'shadow'],
  sixfirhy:           ['demon', 'medium', 'electric', 'lightning'],
  smoke_demon:        ['demon', 'medium', 'smoke', 'cloud'],
  soul_eater:         ['demon', 'large', 'drain', 'soul'],
  sun_demon:          ['demon', 'medium', 'fire', 'light'],
  tentacled_monstrosity: ['demon', 'large', 'tentacle', 'aberrant'],
  tormentor:          ['demon', 'large', 'debuff'],
  ufetubus:           ['demon', 'small', 'flying', 'swarm'],
  ugly_thing:         ['demon', 'medium', 'aberrant', 'multicolor'],
  very_ugly_thing:    ['demon', 'large', 'aberrant', 'multicolor', 'elite'],
  white_imp:          ['demon', 'small', 'cold'],
  ynoxinul:           ['demon', 'medium', 'iron', 'metal'],

  // ── holy ───────────────────────────────────────────────────────────────────
  angel:              ['angel', 'humanoid', 'flying', 'white', 'gold', 'melee'],
  apis:               ['holy', 'bull', 'egyptian', 'large'],
  centaur_paladin:    ['centaur', 'holy', 'melee', 'ranged'],
  cherub:             ['cherub', 'flying', 'small', 'divine', 'fire', 'multi_face'],
  daeva:              ['angel', 'flying', 'elite', 'white', 'gold'],
  eastern_dragon:     ['dragon', 'holy', 'asian', 'divine', 'serpentine'],
  holy_dragon:        ['dragon', 'holy', 'gold', 'white', 'large', 'boss'],
  ophan:              ['celestial', 'wheel', 'divine', 'eyes', 'unusual'],
  paladin:            ['humanoid', 'holy', 'melee', 'armored'],
  seraph_bottom:      ['seraph', 'celestial', 'elite', 'boss', 'two_tile'],
  seraph_top:         ['seraph', 'celestial', 'elite', 'boss', 'two_tile'],
  shedu:              ['holy', 'large', 'winged_bull', 'mesopotamian'],

  // ── nonliving / constructs ─────────────────────────────────────────────────
  air_elemental:      ['elemental', 'air', 'wind', 'intangible', 'flying'],
  ball_lightning:     ['elemental', 'electric', 'lightning', 'explosive', 'small'],
  battlesphere:       ['construct', 'magic', 'small', 'floating'],
  clay_golem:         ['golem', 'clay', 'melee', 'large'],
  crystal_golem:      ['golem', 'crystal', 'melee', 'large', 'reflect'],
  crystal_guardian:   ['golem', 'crystal', 'guard', 'large'],
  earth_elemental:    ['elemental', 'earth', 'stone', 'large', 'melee'],
  electric_golem:     ['golem', 'electric', 'lightning', 'large'],
  fire_elemental:     ['elemental', 'fire', 'flying', 'medium'],
  fire_vortex:        ['elemental', 'fire', 'small', 'spinning', 'animated'],
  flesh_golem:        ['golem', 'organic', 'undead_adjacent', 'large'],
  fulminant_prism:    ['construct', 'magic', 'explosive', 'small', 'animated'],
  gargoyle:           ['gargoyle', 'stone', 'flying', 'medium'],
  guardian_golem:     ['golem', 'construct', 'guard', 'large'],
  insubstantial_wisp: ['elemental', 'intangible', 'small', 'flying'],
  iron_elemental:     ['elemental', 'metal', 'iron', 'large'],
  iron_golem:         ['golem', 'iron', 'metal', 'large', 'melee'],
  maelstrom:          ['elemental', 'air', 'water', 'large', 'spinning', 'animated'],
  metal_gargoyle:     ['gargoyle', 'metal', 'flying', 'medium'],
  molten_gargoyle:    ['gargoyle', 'fire', 'lava', 'flying', 'medium'],
  orb_of_destruction: ['orb', 'magic', 'explosive', 'flying', 'animated'],
  orb_of_electricity: ['orb', 'electric', 'lightning', 'flying', 'animated'],
  orb_of_fire:        ['orb', 'fire', 'flying', 'elite', 'boss'],
  orb_of_ice:         ['orb', 'ice', 'cold', 'flying', 'animated'],
  spatial_vortex:     ['elemental', 'teleport', 'translocation', 'small', 'animated'],
  spectral_axe:       ['spectral_weapon', 'axe', 'melee', 'summoned'],
  spectral_lbl:       ['spectral_weapon', 'sword', 'long_blade', 'melee', 'summoned'],
  spectral_mace:      ['spectral_weapon', 'mace', 'melee', 'summoned'],
  spectral_sbl:       ['spectral_weapon', 'sword', 'short_blade', 'melee', 'summoned'],
  spectral_spear:     ['spectral_weapon', 'spear', 'melee', 'summoned'],
  spectral_staff:     ['spectral_weapon', 'staff', 'melee', 'summoned'],
  spectral_whip:      ['spectral_weapon', 'whip', 'melee', 'summoned'],
  spellforged_servitor: ['construct', 'magic', 'summoned', 'medium'],
  stone_golem:        ['golem', 'stone', 'melee', 'large'],
  toenail_golem:      ['golem', 'chaos', 'unusual', 'medium'],
  twister:            ['elemental', 'air', 'wind', 'large', 'spinning', 'animated'],
  ushabti:            ['construct', 'egyptian', 'undead_adjacent', 'guard', 'large'],
  vapour:             ['elemental', 'gas', 'poison', 'intangible', 'small'],
  water_elemental:    ['elemental', 'water', 'aquatic', 'medium'],
  wellspring:         ['construct', 'magic', 'floating'],
  wood_golem:         ['golem', 'wood', 'organic', 'melee', 'medium'],

  // ── dragons ────────────────────────────────────────────────────────────────
  dragon:             ['dragon', 'red', 'fire', 'large', 'melee'],
  golden_dragon:      ['dragon', 'gold', 'holy', 'poison', 'fire', 'boss'],
  hydra:              ['hydra', 'multi_head', 'large', 'multi_head'],
  ice_dragon:         ['dragon', 'ice', 'cold', 'large'],
  iron_dragon:        ['dragon', 'metal', 'iron', 'large'],
  mottled_dragon:     ['dragon', 'fire', 'medium'],
  quicksilver_dragon: ['dragon', 'magic', 'anti_magic', 'large', 'silver'],
  shadow_dragon:      ['dragon', 'dark', 'shadow', 'large', 'drain'],
  steam_dragon:       ['dragon', 'steam', 'small', 'weak'],
  storm_dragon:       ['dragon', 'lightning', 'electric', 'large'],
  swamp_dragon:       ['dragon', 'poison', 'medium'],
  wyvern:             ['wyvern', 'flying', 'medium', 'melee'],

  // ── unique bosses ─────────────────────────────────────────────────────────
  antaeus:            ['giant', 'large', 'frost', 'cold', 'boss'],
  asmodeus:           ['demon', 'large', 'boss', 'fire', 'hell_lord', 'two_tile'],
  azrael:             ['efreet', 'fire', 'elite', 'boss'],
  boris:              ['lich', 'undead', 'spellcaster', 'respawn'],
  cerebov:            ['demon', 'large', 'boss', 'fire', 'hell_lord', 'sword'],
  dissolution:        ['jelly', 'amorphous', 'acid', 'boss'],
  enchantress:        ['spriggan', 'small', 'enchantment', 'magic', 'buff'],
  ereshkigal:         ['demon', 'large', 'boss', 'cold', 'death', 'hell_lord', 'two_tile'],
  gastronok:          ['slug', 'large', 'acid', 'boss', 'unusual'],
  geryon:             ['demon', 'large', 'boss', 'horn'],
  gloorx_vloq:        ['demon', 'boss', 'dark', 'death', 'hell_lord', 'two_tile'],
  iron_giant:         ['giant', 'iron', 'metal', 'large', 'boss'],
  jormungandr:        ['serpent', 'large', 'boss', 'poison', 'two_tile'],
  lernaean_hydra:     ['hydra', 'boss', 'multi_head', 'large', 'green', 'legendary'],
  lom_lobon:          ['demon', 'boss', 'magic', 'dark', 'hell_lord', 'two_tile'],
  mara:               ['demon', 'illusion', 'boss', 'large'],
  mennas:             ['angel', 'holy', 'boss', 'divine'],
  mnoleg:             ['demon', 'boss', 'chaos', 'green', 'hell_lord', 'two_tile'],
  murray:             ['lich', 'undead', 'spellcaster'],
  polyphemus:         ['giant', 'cyclops', 'large', 'melee'],
  prince_ribbit:      ['frog', 'amphibian', 'polymorph'],
  royal_jelly:        ['jelly', 'large', 'boss', 'amorphous', 'acid', 'summoner'],
  rupert:             ['humanoid', 'large', 'berserker'],
  sigmund:            ['humanoid', 'early_boss', 'scythe', 'undead_adjacent'],
  snorg:              ['troll', 'large', 'melee', 'boss'],
  sojobo:             ['tengu', 'flying', 'elite', 'boss'],
  tiamat:             ['dragon', 'large', 'boss', 'multicolor'],
  xtahua:             ['dragon', 'fire', 'large', 'boss'],

  // ── effects: projectiles (8-directional sprite sheets) ─────────────────────
  arrow:              ['projectile', 'ranged', 'arrow', 'physical', 'dir8'],
  crossbow_bolt:      ['projectile', 'ranged', 'bolt', 'physical', 'dir8'],
  crystal_spear:      ['projectile', 'crystal', 'magic', 'earth', 'dir8'],
  dart:               ['projectile', 'ranged', 'dart', 'physical', 'dir8'],
  icicle:             ['projectile', 'ice', 'cold', 'dir8'],
  iron_shot:          ['projectile', 'iron', 'metal', 'earth', 'physical', 'dir8'],
  javelin:            ['projectile', 'ranged', 'javelin', 'physical', 'dir8'],
  magic_bolt:         ['projectile', 'magic', 'bolt', 'dir8'],
  magic_dart:         ['projectile', 'magic', 'dart', 'small', 'animated'],
  needle:             ['projectile', 'ranged', 'needle', 'physical', 'dir8'],
  poison_arrow:       ['projectile', 'ranged', 'arrow', 'poison', 'dir8'],
  rock:               ['projectile', 'ranged', 'rock', 'physical'],
  sandblast:          ['projectile', 'earth', 'sand', 'small', 'animated'],
  searing_ray:        ['projectile', 'fire', 'light', 'ray', 'animated'],
  sting:              ['projectile', 'poison', 'small', 'animated'],
  stone:              ['projectile', 'ranged', 'stone', 'physical'],
  stone_arrow:        ['projectile', 'earth', 'stone', 'dir8'],
  throwing_net:       ['projectile', 'ranged', 'net', 'trap', 'physical', 'dir8'],
  tomahawk:           ['projectile', 'ranged', 'axe', 'physical', 'dir8'],
  zap:                ['projectile', 'electric', 'lightning', 'small', 'animated'],

  // ── effects: clouds / VFX ────────────────────────────────────────────────
  cloud_acid:             ['cloud', 'acid', 'vfx', 'animated'],
  cloud_black_smoke:      ['cloud', 'smoke', 'dark', 'grey'],
  cloud_blue_smoke:       ['cloud', 'smoke', 'blue'],
  cloud_chaos:            ['cloud', 'chaos', 'multicolor', 'aberrant', 'animated'],
  cloud_cold:             ['cloud', 'cold', 'ice', 'frost', 'animated'],
  cloud_fire:             ['cloud', 'fire', 'flame', 'animated'],
  cloud_forest_fire:      ['cloud', 'fire', 'nature', 'green'],
  cloud_gloom:            ['cloud', 'darkness', 'dark'],
  cloud_grey_smoke:       ['cloud', 'smoke', 'grey'],
  cloud_magic_trail:      ['cloud', 'magic', 'trail', 'sparkle', 'animated'],
  cloud_meph:             ['cloud', 'gas', 'green', 'poison', 'animated'],
  cloud_mutagenic_large:  ['cloud', 'mutagenic', 'chaos', 'pink', 'animated'],
  cloud_mutagenic_medium: ['cloud', 'mutagenic', 'pink'],
  cloud_mutagenic_small:  ['cloud', 'mutagenic', 'tiny', 'pink'],
  cloud_neg:              ['cloud', 'negative_energy', 'drain', 'dark', 'animated'],
  cloud_poison:           ['cloud', 'poison', 'green', 'animated'],
  cloud_rain:             ['cloud', 'rain', 'water', 'weather'],
  cloud_spectral:         ['cloud', 'spectral', 'undead', 'animated'],
  cloud_storm:            ['cloud', 'storm', 'lightning', 'electric'],
  cloud_tloc_energy:      ['cloud', 'translocation', 'teleport', 'purple', 'energy'],
  cloud_yellow_smoke:     ['cloud', 'smoke', 'yellow'],
  acid_venom:             ['vfx', 'acid', 'poison', 'splash'],
  disjunct:               ['vfx', 'translocation', 'teleport', 'purple', 'aoe', 'animated'],
  drain:                  ['vfx', 'drain', 'negative_energy', 'dark', 'animated'],
  drain_red:              ['vfx', 'drain', 'blood', 'life_drain', 'red', 'animated'],
  flame:                  ['vfx', 'fire', 'flame', 'animated', 'small'],
  frost:                  ['vfx', 'ice', 'frost', 'cold', 'animated'],
  gold_sparkles:          ['vfx', 'sparkle', 'gold', 'wealth', 'animated'],
  goldaura:               ['vfx', 'aura', 'gold', 'buff', 'animated'],
  heataura:               ['vfx', 'aura', 'fire', 'heat', 'animated'],
  irradiate:              ['vfx', 'transmutation', 'chaos', 'multicolor', 'aoe', 'animated'],
  orb_glow:               ['vfx', 'orb', 'purple', 'glow', 'animated'],
  sanctuary:              ['vfx', 'holy', 'divine', 'protection', 'circle', 'area_effect'],
  silenced:               ['vfx', 'silence', 'debuff', 'aura', 'status_indicator'],
  tornado:                ['vfx', 'air', 'wind', 'storm', 'large', 'animated'],
  umbra:                  ['vfx', 'darkness', 'shadow', 'dark', 'aura', 'animated'],
  xom_sparkles_blue:      ['vfx', 'chaos', 'sparkle', 'blue'],

  // ── weapons ──────────────────────────────────────────────────────────────
  ancient_sword:      ['sword', 'long_blade', 'one_handed'],
  axe:                ['axe', 'one_handed', 'melee'],
  bardiche:           ['polearm', 'two_handed', 'large_weapon'],
  battle_axe:         ['axe', 'two_handed', 'melee', 'large_weapon'],
  blessed_blade:      ['sword', 'long_blade', 'holy', 'one_handed'],
  broad_axe:          ['axe', 'one_handed', 'melee'],
  bullwhip:           ['whip', 'one_handed'],
  claymore:           ['sword', 'long_blade', 'two_handed', 'large_weapon'],
  club:               ['club', 'one_handed', 'primitive'],
  cutlass:            ['sword', 'short_blade', 'one_handed'],
  dagger:             ['dagger', 'short_blade', 'one_handed', 'small_weapon'],
  demon_blade:        ['sword', 'demon', 'dark', 'one_handed'],
  demon_trident:      ['trident', 'polearm', 'demon', 'dark'],
  demon_whip:         ['whip', 'demon', 'dark'],
  dire_flail:         ['flail', 'two_handed', 'large_weapon'],
  double_sword:       ['sword', 'long_blade', 'two_handed'],
  executioner_axe:    ['axe', 'two_handed', 'large_weapon'],
  falchion:           ['sword', 'long_blade', 'one_handed'],
  flail:              ['flail', 'one_handed', 'chain'],
  glaive:             ['polearm', 'blade', 'two_handed', 'large_weapon'],
  greatsword:         ['sword', 'long_blade', 'two_handed', 'large_weapon'],
  halberd:            ['polearm', 'two_handed', 'large_weapon'],
  hand_axe:           ['axe', 'one_handed', 'small_weapon', 'throwing'],
  hand_crossbow:      ['crossbow', 'ranged', 'one_handed', 'small_weapon'],
  holy_scourge:       ['flail', 'holy', 'divine'],
  katana:             ['sword', 'long_blade', 'one_handed'],
  lajatang:           ['double_ended', 'two_handed', 'unusual'],
  long_sword:         ['sword', 'long_blade', 'one_handed'],
  mace:               ['mace', 'one_handed'],
  morningstar:        ['mace', 'spiky', 'one_handed'],
  quarterstaff:       ['staff', 'two_handed', 'blunt', 'physical'],
  quickblade:         ['sword', 'short_blade', 'fast', 'one_handed'],
  rapier:             ['sword', 'short_blade', 'piercing', 'one_handed'],
  scythe:             ['polearm', 'two_handed', 'unusual'],
  short_sword:        ['sword', 'short_blade', 'one_handed', 'small_weapon'],
  spear:              ['spear', 'polearm', 'one_handed', 'throwing'],
  trident:            ['trident', 'polearm', 'one_handed'],
  two_handed_sword:   ['sword', 'long_blade', 'two_handed', 'large_weapon'],
  war_axe:            ['axe', 'one_handed', 'melee'],
  war_hammer:         ['mace', 'hammer', 'two_handed', 'large_weapon'],
  bow:                ['bow', 'ranged', 'two_handed'],
  crossbow:           ['crossbow', 'ranged', 'two_handed'],
  longbow:            ['bow', 'ranged', 'two_handed', 'heavy'],
  shortbow:           ['bow', 'ranged', 'two_handed', 'light'],
  arbalest:           ['crossbow', 'ranged', 'two_handed', 'heavy'],
  blowgun:            ['blowgun', 'ranged', 'one_handed', 'poison'],
  greatsling:         ['sling', 'ranged', 'two_handed'],
  sling:              ['sling', 'ranged', 'one_handed'],

  // ── armor ─────────────────────────────────────────────────────────────────
  robe:               ['armor', 'light', 'caster', 'cloth'],
  chain_mail:         ['armor', 'medium', 'metal', 'chainmail'],
  crystal_plate_mail: ['armor', 'heavy', 'crystal', 'reflect', 'rare'],
  troll_leather_armor: ['armor', 'medium', 'troll', 'regen'],
  gold_dragon_armor:  ['armor', 'heavy', 'dragon_scale', 'gold', 'fire', 'poison', 'cold'],
  shadow_dragon_scale_mail: ['armor', 'heavy', 'dragon_scale', 'dark', 'shadow'],
  silver_dragon_scale_mail: ['armor', 'heavy', 'dragon_scale', 'silver', 'resist'],

  // ── altars & deity icons ──────────────────────────────────────────────────
  altar_shining_one:  ['altar', 'holy', 'gold', 'divine', 'light'],
  altar_trog:         ['altar', 'berserker', 'warrior', 'red', 'blood'],
  altar_kikubaaqudgha: ['altar', 'necromancy', 'death', 'dark', 'skull'],
  altar_makhleb:      ['altar', 'demon', 'fire', 'animated', 'flame'],
  altar_vehumet:      ['altar', 'conjuration', 'magic', 'blue'],
  altar_fedhas:       ['altar', 'nature', 'plant', 'dark_green'],
  altar_jiyva:        ['altar', 'slime', 'chaos', 'animated'],
  altar_xom:          ['altar', 'chaos', 'multicolor', 'animated'],
  altar_yredelemnul:  ['altar', 'undead', 'death', 'dark'],
  altar_zin:          ['altar', 'law', 'purity', 'silver'],
  altar_cheibriados:  ['altar', 'time', 'slow', 'animated'],
  altar_elyvilon:     ['altar', 'healing', 'white', 'peaceful'],
  altar_sif_muna:     ['altar', 'magic', 'knowledge', 'blue'],
  altar_okawaru:      ['altar', 'combat', 'warrior', 'shield'],
  altar_nemelex_xobeh: ['altar', 'cards', 'chaos'],
  altar_lugonu:       ['altar', 'chaos', 'abyss', 'dark', 'purple'],
  altar_beogh:        ['altar', 'orc', 'tribal'],
  altar_ashenzari:    ['altar', 'knowledge', 'chains', 'necromancy'],

  // ── emissaries — DCSS 六神明（分体精灵，top+bottom 搭配使用）──────────────
  elyvilon_top:       ['deity', 'god', 'healing', 'peaceful', 'white', 'two_tile'],
  elyvilon_bottom:    ['deity', 'god', 'healing', 'peaceful', 'white', 'two_tile'],
  okawaru_top:        ['deity', 'god', 'combat', 'warrior', 'armor', 'two_tile'],
  okawaru_bottom:     ['deity', 'god', 'combat', 'warrior', 'armor', 'two_tile'],
  trog_top:           ['deity', 'god', 'berserker', 'rage', 'warrior', 'red', 'two_tile'],
  trog_bottom:        ['deity', 'god', 'berserker', 'rage', 'warrior', 'red', 'two_tile'],
  tso_top:            ['deity', 'god', 'holy', 'divine', 'gold', 'light', 'two_tile'],
  tso_bottom:         ['deity', 'god', 'holy', 'divine', 'gold', 'light', 'two_tile'],
  vehumet_top:        ['deity', 'god', 'fire', 'magic', 'conjuration', 'blue', 'two_tile'],
  vehumet_bottom:     ['deity', 'god', 'fire', 'magic', 'conjuration', 'blue', 'two_tile'],
  zin_top:            ['deity', 'god', 'law', 'purity', 'order', 'silver', 'two_tile'],
  zin_bottom:         ['deity', 'god', 'law', 'purity', 'order', 'silver', 'two_tile'],

  // ── Balatro 花色图标 & 特殊卡牌 ──────────────────────────────────────────
  Club_suit_icon:     ['suit', 'club', 'playing_card', 'poker', 'black'],
  Diamond_suit_icon:  ['suit', 'diamond', 'playing_card', 'poker', 'red'],
  Heart_suit_icon:    ['suit', 'heart', 'playing_card', 'poker', 'red'],
  Spade_suit_icon:    ['suit', 'spade', 'playing_card', 'poker', 'black'],
  BalatroHands:       ['poker_hand', 'reference', 'game_guide', 'chart'],
  Blinds:             ['blind', 'boss_blind', 'ante', 'objective'],
  Editions:           ['edition', 'foil', 'holographic', 'polychrome', 'negative'],
  Enhanced_Cards:     ['enhanced', 'seal', 'card_modifier', 'bonus'],
  Vouchers:           ['voucher', 'shop_item', 'permanent_buff'],
  Locked_Deck:        ['deck', 'locked', 'unlock', 'game_mode'],
  Tarot_Judgement:    ['tarot', 'consumable', 'special_card', 'soul_card'],
  Tarot_The_Fool:     ['tarot', 'consumable', 'special_card', 'soul_card'],
  Planet_Eris:        ['planet', 'hand_level', 'consumable', 'rare'],
  Spectral_Cryptid:   ['spectral', 'consumable', 'special_card', 'rare'],
  Spectral_Grim:      ['spectral', 'consumable', 'special_card', 'rare'],
  Pair_of_4:          ['poker_hand', 'pair', 'playing_card', 'hand_example'],
};
