import type { AssetManifest } from '@assets/index.js';

// ════════════════════════════════════════════════════════════════════════
//  Game E · 小丑美术资产清单（纯数据：key → 图源）
//  图源 = assets/FreeArtLib/cardgame/card/（用户提供，commit "card2"）。
//  sim 只引用 textureKey，像素活在资产层、绝不进 hash → lockstep 安全。
//  覆盖：109/150 官方小丑有图；其余 41 张暂缺，渲染退化占位方块（sim 不受影响），补图即加行。
//  约定：小丑美术 key = je.joker.<官方蛇形 id>，与 jokers.ts 的 id 对齐。
// ════════════════════════════════════════════════════════════════════════

const CARD_DIR = 'assets/FreeArtLib/cardgame/card';

/** 小丑美术的 texture key（与 jokers 数据的 id 对齐）。 */
export const jokerArtKey = (id: string): string => `je.joker.${id}`;

/** 已落地美术的官方小丑（id → 文件名），共 109 张。 */
export const JOKER_ART_FILES: ReadonlyArray<{ readonly id: string; readonly file: string }> = [
  { id: "joker", file: "Joker.webp" },
  { id: "greedy_joker", file: "Greedy_Joker.webp" },
  { id: "lusty_joker", file: "Lusty_Joker.webp" },
  { id: "wrathful_joker", file: "Wrathful_Joker.webp" },
  { id: "gluttonous_joker", file: "Gluttonous_Joker.webp" },
  { id: "jolly_joker", file: "Jolly_Joker.webp" },
  { id: "zany_joker", file: "Zany_Joker.webp" },
  { id: "mad_joker", file: "Mad_Joker.webp" },
  { id: "crazy_joker", file: "Crazy_Joker.webp" },
  { id: "droll_joker", file: "Droll_Joker.webp" },
  { id: "sly_joker", file: "Sly_Joker.webp" },
  { id: "wily_joker", file: "Wily_Joker.webp" },
  { id: "clever_joker", file: "Clever_Joker.webp" },
  { id: "devious_joker", file: "Devious_Joker.webp" },
  { id: "crafty_joker", file: "Crafty_Joker.webp" },
  { id: "half_joker", file: "Half_Joker.webp" },
  { id: "gros_michel", file: "Gros_Michel.webp" },
  { id: "scholar", file: "Scholar.webp" },
  { id: "business_card", file: "Business_Card.webp" },
  { id: "supernova", file: "Supernova.webp" },
  { id: "ride_the_bus", file: "Ride_the_Bus.webp" },
  { id: "space_joker", file: "Space_Joker.webp" },
  { id: "egg", file: "Egg.webp" },
  { id: "burglar", file: "Burglar.webp" },
  { id: "blackboard", file: "Blackboard.webp" },
  { id: "runner", file: "Runner.webp" },
  { id: "ice_cream", file: "Ice_Cream.webp" },
  { id: "dna", file: "DNA.webp" },
  { id: "splash", file: "Splash.webp" },
  { id: "blue_joker", file: "Blue_Joker.webp" },
  { id: "sixth_sense", file: "Sixth_Sense.webp" },
  { id: "constellation", file: "Constellation.webp" },
  { id: "hiker", file: "Hiker.webp" },
  { id: "faceless_joker", file: "Faceless_Joker.webp" },
  { id: "green_joker", file: "Green_Joker.webp" },
  { id: "superposition", file: "Superposition.webp" },
  { id: "to_do_list", file: "To_Do_List.webp" },
  { id: "cavendish", file: "Cavendish.webp" },
  { id: "card_sharp", file: "Card_Sharp.webp" },
  { id: "red_card", file: "Red_Card.webp" },
  { id: "madness", file: "Madness.webp" },
  { id: "square_joker", file: "Square_Joker.webp" },
  { id: "s_ance", file: "S_ance.webp" },
  { id: "riff_raff", file: "Riff-Raff.webp" },
  { id: "vampire", file: "Vampire.webp" },
  { id: "shortcut", file: "Shortcut.webp" },
  { id: "hologram", file: "Hologram.webp" },
  { id: "vagabond", file: "Vagabond.webp" },
  { id: "baron", file: "Baron.webp" },
  { id: "cloud_9", file: "Cloud_9.webp" },
  { id: "rocket", file: "Rocket.webp" },
  { id: "obelisk", file: "Obelisk.webp" },
  { id: "midas_mask", file: "Midas_Mask.webp" },
  { id: "luchador", file: "Luchador.webp" },
  { id: "photograph", file: "Photograph.webp" },
  { id: "gift_card", file: "Gift_Card.webp" },
  { id: "turtle_bean", file: "Turtle_Bean.webp" },
  { id: "erosion", file: "Erosion.webp" },
  { id: "reserved_parking", file: "Reserved_Parking.webp" },
  { id: "mail_in_rebate", file: "Mail-In_Rebate.webp" },
  { id: "to_the_moon", file: "To_the_Moon.webp" },
  { id: "hallucination", file: "Hallucination.webp" },
  { id: "fortune_teller", file: "Fortune_Teller.webp" },
  { id: "juggler", file: "Juggler.webp" },
  { id: "drunkard", file: "Drunkard.webp" },
  { id: "stone_joker", file: "Stone_Joker.webp" },
  { id: "golden_joker", file: "Golden_Joker.webp" },
  { id: "walkie_talkie", file: "Walkie_Talkie.webp" },
  { id: "seltzer", file: "Seltzer.webp" },
  { id: "castle", file: "Castle.webp" },
  { id: "smiley_face", file: "Smiley_Face.webp" },
  { id: "campfire", file: "Campfire.webp" },
  { id: "golden_ticket", file: "Golden_Ticket.webp" },
  { id: "mr_bones", file: "Mr._Bones.webp" },
  { id: "acrobat", file: "Acrobat.webp" },
  { id: "sock_and_buskin", file: "Sock_and_Buskin.webp" },
  { id: "swashbuckler", file: "Swashbuckler.webp" },
  { id: "troubadour", file: "Troubadour.webp" },
  { id: "certificate", file: "Certificate.webp" },
  { id: "smeared_joker", file: "Smeared_Joker.webp" },
  { id: "throwback", file: "Throwback.webp" },
  { id: "hanging_chad", file: "Hanging_Chad.webp" },
  { id: "rough_gem", file: "Rough_Gem.webp" },
  { id: "bloodstone", file: "Bloodstone.webp" },
  { id: "arrowhead", file: "Arrowhead.webp" },
  { id: "showman", file: "Showman.webp" },
  { id: "seeing_double", file: "Seeing_Double.webp" },
  { id: "matador", file: "Matador.webp" },
  { id: "hit_the_road", file: "Hit_the_Road.webp" },
  { id: "the_duo", file: "The_Duo.webp" },
  { id: "the_trio", file: "The_Trio.webp" },
  { id: "the_family", file: "The_Family.webp" },
  { id: "the_order", file: "The_Order.webp" },
  { id: "the_tribe", file: "The_Tribe.webp" },
  { id: "stuntman", file: "Stuntman.webp" },
  { id: "invisible_joker", file: "Invisible_Joker.webp" },
  { id: "brainstorm", file: "Brainstorm.webp" },
  { id: "satellite", file: "Satellite.webp" },
  { id: "shoot_the_moon", file: "Shoot_the_Moon.webp" },
  { id: "driver_s_license", file: "Driver's_License.webp" },
  { id: "cartomancer", file: "Cartomancer.webp" },
  { id: "astronomer", file: "Astronomer.webp" },
  { id: "burnt_joker", file: "Burnt_Joker.webp" },
  { id: "bootstraps", file: "Bootstraps.webp" },
  { id: "canio", file: "Canio.webp" },
  { id: "triboulet", file: "Triboulet.webp" },
  { id: "yorick", file: "Yorick.webp" },
  { id: "chicot", file: "Chicot.webp" },
  { id: "perkeo", file: "Perkeo.webp" },
];

/** 暂缺美术的官方小丑 id（渲染走占位方块），共 41 张。补图后从此移到 JOKER_ART_FILES。 */
export const JOKER_ART_MISSING: readonly string[] = ["joker_stencil","four_fingers","mime","credit_card","ceremonial_dagger","banner","mystic_summit","marble_joker","loyalty_card","8_ball","misprint","dusk","raised_fist","chaos_the_clown","fibonacci","steel_joker","scary_face","abstract_joker","delayed_gratification","hack","pareidolia","even_steven","odd_todd","lucky_cat","baseball_card","bull","diet_cola","trading_card","flash_card","popcorn","spare_trousers","ancient_joker","ramen","onyx_agate","glass_joker","flower_pot","blueprint","wee_joker","merry_andy","oops_all_6s","the_idol"];

/** 资产清单：把 109 条 id→文件 展开成 texture 描述符，喂给 AssetManager。 */
export const JOKER_ART_MANIFEST: AssetManifest = JOKER_ART_FILES.map(({ id, file }) => ({
  kind: 'texture' as const,
  key: jokerArtKey(id),
  src: `${CARD_DIR}/${file}`,
}));
